const data = {
  product: [
    {
      name: 'Bookinees',
      image: 'Images/women/heels07.avif',
      brand: ' Jimmy Choo',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      image: 'Images/women/high-heels-1.jpg',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Stuart Weitzman Nudis',
      brand: 'Stuart Weitzman',
      price: '8 000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '12 000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Jimmy Choo Romy',
      brand: 'Jimmy Choo',
      price: '10000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Jimmy Choo Romy',
      brand: 'Jimmy Choo',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Gucci Marmont',
      brand: 'Gucci',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      name: 'Jimmy Choo Romy',
      brand: 'Jimmy Choo',
      price: '8000 frs',
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
  ],
};

export default data;
