version: '3.8'
services:
  client:
    image: shopee_client:latest
    build: ./client
    #dockerfile: Dockerfile
    container_name: shopee_client_container
    restart: always
    volumes:
      - ./client:/client
    ports:
      - 3000:80
    stdin_open: true
