const data = {
  products: [
    {
      id: 1,
      name: 'Bookinees',
      image: '/Images/women/heels/heels02.png',
      brand: ' Jimmy Choo',
      price: 8000,
      category: 'women',
      subcategory: 'heels',
      countInStock: 4,
      rating: 1.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 2,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels01.png',
      brand: 'Gucci',
      price: 12000,
      category: 'women',
      subcategory: 'heels',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 3,
      name: 'Stuart Weitzman Nudis',
      image: '/Images/women/heels/heels03.png',
      brand: 'Stuart Weitzman',
      price: 8000,
      category: 'women',
      subcategory: 'heels',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 4,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 12000,
      category: 'women',
      subcategory: 'heels',
      countInStock: 4,
      rating: 3.5,
      newArrival: true,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 5,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 10000,
      category: 'women',
      countInStock: 4,
      rating: 4.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 6,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 7,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 8,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 9,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 10,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 11,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 12,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: false,
      trending: true,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 13,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: '8000',
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 14,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 15,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 16,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 17,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      featured: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 18,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      featured: true,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 19,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'men',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 20,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'women',
      subcategory: 'Tennis',
      image: 'Images/banner/arr-img.png',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 21,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      featured: true,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 22,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      bestSeller: true,
      featured: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 23,
      name: 'Gucci Marmont',
      image: '/Images/women/heels/heels04.png',
      brand: 'Gucci',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      featured: true,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 24,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: false,
      featured: true,
      bestSeller: true,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 25,
      name: 'Jimmy Choo Romy',
      image: '/Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: true,
      featured: false,
      bestSeller: false,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 26,
      name: '/Jimmy Choo Romy',
      image: 'Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: true,
      featured: false,
      bestSeller: false,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
    {
      id: 27,
      name: '/Jimmy Choo Romy',
      image: 'Images/women/heels/heels04.png',
      brand: 'Jimmy Choo',
      price: 8000,
      category: 'women',
      countInStock: 4,
      rating: 3.5,
      newArrival: true,
      featured: false,
      bestSeller: false,
      trending: false,
      numReview: 10,
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor',
    },
  ],
};

export default data;
